import { Link } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { AlertTriangle, ArrowLeft } from "lucide-react";

const Disclaimer = () => {
  return (
    <div className="min-h-dvh bg-background overflow-x-hidden">
      <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6">
        <Button asChild variant="ghost" size="sm" className="mb-6">
          <Link to="/">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to app
          </Link>
        </Button>

        <div className="mb-8 flex items-center gap-3">
          <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-amber-500/15">
            <AlertTriangle className="h-6 w-6 text-amber-500" />
          </div>
          <div>
            <h1 className="text-2xl font-bold sm:text-3xl">Medical Disclaimer</h1>
            <p className="text-sm text-muted-foreground">Last updated: August 2026</p>
          </div>
        </div>

        <Card className="border-amber-500/40 bg-amber-500/5">
          <CardHeader>
            <CardTitle className="text-amber-600 dark:text-amber-400">
              Important — Please Read Carefully
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 text-sm leading-relaxed">
            <p className="font-semibold text-foreground">
              This app is for informational and educational purposes only and does not provide
              medical diagnosis, treatment, or emergency advice. Always consult a doctor before
              making medical decisions.
            </p>
          </CardContent>
        </Card>

        <Separator className="my-8" />

        <div className="space-y-8">
          <section>
            <h2 className="mb-3 text-lg font-semibold">Not a Substitute for Professional Care</h2>
            <Card>
              <CardContent className="space-y-3 pt-6 text-sm leading-relaxed text-muted-foreground">
                <p>
                  The Syncope &amp; Loss of Consciousness Assessment application is a clinical
                  reference and documentation tool intended for use by healthcare professionals,
                  clinicians, residents, and medical students. It is provided for educational and
                  informational purposes only.
                </p>
                <p>
                  The app does not provide medical diagnosis, treatment, triage, or emergency
                  advice, and it is not a substitute for the professional judgment of a qualified
                  healthcare provider. Nothing in this app should be interpreted as a
                  recommendation for a specific course of treatment.
                </p>
              </CardContent>
            </Card>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold">Descriptive, Not Directive</h2>
            <Card>
              <CardContent className="space-y-3 pt-6 text-sm leading-relaxed text-muted-foreground">
                <p>
                  Results, scores, and interpretations generated by the app are descriptive and
                  educational. They are based on established clinical criteria and published
                  literature, but they do not constitute a diagnosis or a treatment plan.
                </p>
                <p>
                  Clinical decisions must always be individualized based on the complete clinical
                  context and made by a qualified healthcare professional.
                </p>
              </CardContent>
            </Card>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold">Emergency Situations</h2>
            <Card>
              <CardContent className="space-y-3 pt-6 text-sm leading-relaxed text-muted-foreground">
                <p>
                  This app is not intended for use in emergency situations. If you or someone
                  else is experiencing a medical emergency, call your local emergency services
                  immediately. Do not delay seeking professional medical care because of
                  something you read in this app.
                </p>
              </CardContent>
            </Card>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold">No Warranty</h2>
            <Card>
              <CardContent className="space-y-3 pt-6 text-sm leading-relaxed text-muted-foreground">
                <p>
                  The app is provided "as is" without warranties of any kind, either express or
                  implied. While we strive for accuracy, we make no representations or
                  warranties regarding the completeness, accuracy, reliability, suitability, or
                  availability of the information provided.
                </p>
                <p>
                  To the maximum extent permitted by law, we disclaim all liability for any loss
                  or damage arising from the use of, or reliance on, the information in this app.
                </p>
              </CardContent>
            </Card>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold">Consult Your Healthcare Provider</h2>
            <Card>
              <CardContent className="space-y-3 pt-6 text-sm leading-relaxed text-muted-foreground">
                <p>
                  Always consult a doctor or other qualified healthcare provider before making
                  any medical decisions, before starting or changing any treatment, and for any
                  questions you may have regarding a medical condition.
                </p>
              </CardContent>
            </Card>
          </section>
        </div>

        <Separator className="my-8" />
        <p className="text-center text-xs text-muted-foreground">
          © 2026 Syncope &amp; Loss of Consciousness Assessment. All rights reserved.
        </p>
      </div>
    </div>
  );
};

export default Disclaimer;
