import { Link } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { FileText, ArrowLeft, Mail } from "lucide-react";

const TermsOfUse = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6">
        <Button asChild variant="ghost" size="sm" className="mb-6">
          <Link to="/">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to app
          </Link>
        </Button>

        <div className="mb-8 flex items-center gap-3">
          <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10">
            <FileText className="h-6 w-6 text-primary" />
          </div>
          <div>
            <h1 className="text-2xl font-bold sm:text-3xl">Terms of Use</h1>
            <p className="text-sm text-muted-foreground">Last updated: August 2026</p>
          </div>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Agreement to Terms</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 text-sm leading-relaxed text-muted-foreground">
            <p>
              By accessing or using the Syncope &amp; Loss of Consciousness Assessment
              application ("the app"), you agree to be bound by these Terms of Use. If you
              do not agree to these terms, please do not use the app.
            </p>
          </CardContent>
        </Card>

        <Separator className="my-8" />

        <div className="space-y-8">
          <section>
            <h2 className="mb-3 text-lg font-semibold">1. Medical Disclaimer</h2>
            <Card>
              <CardContent className="space-y-3 pt-6 text-sm leading-relaxed text-muted-foreground">
                <p>
                  <strong className="text-foreground">This app is for informational and educational purposes only and does not provide medical diagnosis, treatment, or emergency advice. Always consult a doctor before making medical decisions.</strong>
                </p>
                <p>
                  The app is a clinical reference and documentation tool intended for use by
                  healthcare professionals, clinicians, residents, and medical students. It is
                  not a substitute for professional medical judgment, and it does not replace
                  the clinical evaluation of a qualified healthcare provider.
                </p>
                <p>
                  Results generated by the app are descriptive and educational. They do not
                  constitute a diagnosis, treatment recommendation, triage decision, or
                  emergency-care instruction. In an emergency, call your local emergency
                  services immediately.
                </p>
              </CardContent>
            </Card>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold">2. Use of the Service</h2>
            <Card>
              <CardContent className="space-y-3 pt-6 text-sm leading-relaxed text-muted-foreground">
                <p>You agree to use the app only for lawful purposes and in accordance with these Terms. You agree not to:</p>
                <ul className="list-disc space-y-1 pl-5">
                  <li>Use the app in any way that violates applicable laws or regulations.</li>
                  <li>Attempt to gain unauthorized access to the app, its servers, or other users' accounts.</li>
                  <li>Misuse the app to provide medical advice to others in a manner that is unsafe or unlawful.</li>
                  <li>Interfere with or disrupt the operation of the service.</li>
                </ul>
              </CardContent>
            </Card>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold">3. Accounts</h2>
            <Card>
              <CardContent className="space-y-3 pt-6 text-sm leading-relaxed text-muted-foreground">
                <p>
                  To use certain features, you may create an account. You are responsible for
                  maintaining the confidentiality of your login credentials and for all
                  activity that occurs under your account. You agree to notify us immediately
                  of any unauthorized use of your account.
                </p>
                <p>
                  You may delete your account at any time from the app's account/settings
                  screen. Deleting your account permanently removes your authentication record
                  and all associated data.
                </p>
              </CardContent>
            </Card>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold">4. Intellectual Property</h2>
            <Card>
              <CardContent className="space-y-3 pt-6 text-sm leading-relaxed text-muted-foreground">
                <p>
                  The app, including its software, design, text, graphics, and other content,
                  is owned by us or our licensors and is protected by applicable intellectual
                  property laws. You may not copy, modify, distribute, or create derivative
                  works from any part of the app without our prior written consent.
                </p>
              </CardContent>
            </Card>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold">5. Limitation of Liability</h2>
            <Card>
              <CardContent className="space-y-3 pt-6 text-sm leading-relaxed text-muted-foreground">
                <p>
                  To the maximum extent permitted by law, we shall not be liable for any
                  indirect, incidental, special, consequential, or punitive damages, or any
                  loss of profits or revenues, whether incurred directly or indirectly, or any
                  loss of data, arising from your use of the app.
                </p>
                <p>
                  The app is provided "as is" and "as available" without warranties of any
                  kind, either express or implied, including but not limited to implied
                  warranties of merchantability, fitness for a particular purpose, and
                  non-infringement.
                </p>
              </CardContent>
            </Card>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold">6. Changes to These Terms</h2>
            <Card>
              <CardContent className="space-y-3 pt-6 text-sm leading-relaxed text-muted-foreground">
                <p>
                  We may revise these Terms of Use from time to time. The most current version
                  will always be posted on this page. By continuing to use the app after
                  changes are posted, you agree to the revised terms.
                </p>
              </CardContent>
            </Card>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold">7. Contact Us</h2>
            <Card>
              <CardContent className="space-y-3 pt-6 text-sm leading-relaxed text-muted-foreground">
                <p>If you have any questions about these Terms of Use, please contact us:</p>
                <p className="flex items-center gap-2">
                  <Mail className="h-4 w-4 text-primary" />
                  <a href="mailto:support@medcalc.example.com" className="text-primary underline">
                    support@medcalc.example.com
                  </a>
                </p>
              </CardContent>
            </Card>
          </section>
        </div>

        <Separator className="my-8" />
        <p className="text-center text-xs text-muted-foreground">
          © 2026 Syncope &amp; Loss of Consciousness Assessment. All rights reserved.
        </p>
      </div>
    </div>
  );
};

export default TermsOfUse;
